remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: PAMAGOO Store
description: Bookmark this page to get in touch with us!
